[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd backend && npm install --production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[phases.start]
cmd = "cd backend && node server.js"