[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksConfig]
buildCommand = "cd backend && npm install"