[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksConfig]
buildCommand = "npm install"

[build.nixpacksConfig.phases.setup]
nixPkgs = ["nodejs", "npm"]

[build.nixpacksConfig.phases.build]
cmds = ["cd backend && npm install"]

[build.nixpacksConfig.phases.start]
cmd = "cd backend && npm start"