[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
workingDirectory = "/app/backend"

[build.nixpacksConfig]
buildCommand = "npm install"
workingDirectory = "/app/backend"